/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) forward_derivatives_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* eval_forward_derivatives:(i0[3],i1[3],i2[3])->(o0[3x3],o1[3x3],o2[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=-1.9620000000000002e+02;
  a1=10.;
  a2=arg[0]? arg[0][1] : 0;
  a3=cos(a2);
  a4=arg[1]? arg[1][1] : 0;
  a5=arg[1]? arg[1][0] : 0;
  a6=(a3*a5);
  a7=(a4*a6);
  a2=sin(a2);
  a8=arg[2]? arg[2][0] : 0;
  a9=(a2*a5);
  a10=(a3*a9);
  a11=(a2*a6);
  a10=(a10-a11);
  a11=arg[0]? arg[0][0] : 0;
  a12=(a11*a4);
  a12=(a10+a12);
  a13=5.0000000000000000e-01;
  a14=(a13*a2);
  a14=(a11+a14);
  a15=(a14*a4);
  a15=(a12-a15);
  a15=(a1*a15);
  a16=(a4*a15);
  a17=(a3*a16);
  a18=(a3*a6);
  a19=(a2*a9);
  a18=(a18+a19);
  a19=(a13*a3);
  a20=(a19*a4);
  a20=(a18+a20);
  a20=(a1*a20);
  a21=(a4*a20);
  a22=(a2*a21);
  a17=(a17+a22);
  a22=arg[0]? arg[0][2] : 0;
  a23=cos(a22);
  a24=(a3*a23);
  a22=sin(a22);
  a25=(a2*a22);
  a24=(a24-a25);
  a25=arg[1]? arg[1][2] : 0;
  a26=(a25+a4);
  a27=(a3*a23);
  a28=(a2*a22);
  a27=(a27-a28);
  a28=(a13*a4);
  a6=(a6+a28);
  a28=(a22*a6);
  a29=(a23*a9);
  a28=(a28+a29);
  a29=(a27*a28);
  a30=(a2*a23);
  a31=(a3*a22);
  a30=(a30+a31);
  a6=(a23*a6);
  a31=(a22*a9);
  a6=(a6-a31);
  a31=(a30*a6);
  a29=(a29-a31);
  a31=(a13*a2);
  a31=(a11+a31);
  a32=(a31*a26);
  a32=(a29+a32);
  a33=(a3*a22);
  a34=(a2*a23);
  a33=(a33+a34);
  a34=(a13*a33);
  a35=(a31+a34);
  a36=(a35*a26);
  a36=(a32-a36);
  a36=(a1*a36);
  a37=(a26*a36);
  a38=(a24*a37);
  a39=(a24*a6);
  a40=(a33*a28);
  a39=(a39+a40);
  a40=(a13*a3);
  a41=(a40*a26);
  a41=(a39-a41);
  a42=(a13*a27);
  a43=(a40+a42);
  a44=(a43*a26);
  a44=(a41+a44);
  a44=(a1*a44);
  a45=(a26*a44);
  a46=(a30*a45);
  a38=(a38+a46);
  a46=1.4285714285714284e+00;
  a47=arg[2]? arg[2][2] : 0;
  a48=(a32*a44);
  a49=(a41*a36);
  a48=(a48-a49);
  a49=(a40*a37);
  a50=(a31*a45);
  a49=(a49+a50);
  a48=(a48-a49);
  a48=(a47-a48);
  a49=(a46*a48);
  a50=2.8571428571428577e+00;
  a28=(a25*a28);
  a51=(a50*a28);
  a49=(a49-a51);
  a38=(a38+a49);
  a49=(a23*a38);
  a37=(a33*a37);
  a45=(a27*a45);
  a37=(a37-a45);
  a25=(a25*a6);
  a6=(a1*a25);
  a37=(a37+a6);
  a6=(a22*a37);
  a49=(a49+a6);
  a17=(a17+a49);
  a6=(a1*a22);
  a45=(a6*a23);
  a51=(a50*a23);
  a52=(a51*a22);
  a45=(a45-a52);
  a52=5.;
  a51=(a51*a23);
  a6=(a6*a22);
  a51=(a51+a6);
  a6=(a13*a51);
  a53=8.8817841970012523e-16;
  a54=(a53*a23);
  a6=(a6+a54);
  a55=(a52+a6);
  a56=3.5000000000000000e+00;
  a54=(a13*a54);
  a6=(a13*a6);
  a54=(a54+a6);
  a54=(a56+a54);
  a6=(a55/a54);
  a57=(a13*a45);
  a53=(a53*a22);
  a57=(a57-a53);
  a53=(a6*a57);
  a45=(a45-a53);
  a53=(a45*a7);
  a51=(a1+a51);
  a58=(a6*a55);
  a51=(a51-a58);
  a9=(a4*a9);
  a58=(a51*a9);
  a53=(a53-a58);
  a58=arg[2]? arg[2][1] : 0;
  a59=(a12*a20);
  a60=(a18*a15);
  a59=(a59-a60);
  a60=(a11*a21);
  a59=(a59-a60);
  a49=(a13*a49);
  a47=(a47+a49);
  a59=(a59+a47);
  a58=(a58-a59);
  a59=(a6*a58);
  a53=(a53+a59);
  a17=(a17+a53);
  a17=(a3*a17);
  a16=(a2*a16);
  a21=(a3*a21);
  a16=(a16-a21);
  a37=(a23*a37);
  a38=(a22*a38);
  a37=(a37-a38);
  a16=(a16+a37);
  a50=(a50*a22);
  a37=(a50*a22);
  a38=(a1*a23);
  a21=(a38*a23);
  a37=(a37+a21);
  a37=(a1+a37);
  a21=(a57/a54);
  a53=(a21*a57);
  a37=(a37-a53);
  a53=(a37*a7);
  a38=(a38*a22);
  a50=(a50*a23);
  a38=(a38-a50);
  a50=(a21*a55);
  a38=(a38-a50);
  a50=(a38*a9);
  a53=(a53-a50);
  a50=(a21*a58);
  a53=(a53+a50);
  a16=(a16+a53);
  a16=(a2*a16);
  a17=(a17+a16);
  a8=(a8-a17);
  a17=1.;
  a16=(a3*a51);
  a53=(a2*a38);
  a16=(a16+a53);
  a16=(a16*a3);
  a53=(a3*a45);
  a50=(a2*a37);
  a53=(a53+a50);
  a53=(a53*a2);
  a16=(a16+a53);
  a16=(a17+a16);
  a8=(a8/a16);
  a53=9.8100000000000005e+00;
  a38=(a3*a38);
  a51=(a2*a51);
  a38=(a38-a51);
  a38=(a38*a3);
  a37=(a3*a37);
  a45=(a2*a45);
  a37=(a37-a45);
  a37=(a37*a2);
  a38=(a38+a37);
  a38=(a38/a16);
  a38=(a53*a38);
  a8=(a8-a38);
  a38=(a2*a8);
  a37=(a53*a3);
  a38=(a38+a37);
  a7=(a7+a38);
  a38=(a3*a7);
  a37=(a3*a8);
  a53=(a53*a2);
  a37=(a37-a53);
  a37=(a37-a9);
  a9=(a2*a37);
  a38=(a38-a9);
  a58=(a58/a54);
  a9=(a6*a37);
  a53=(a21*a7);
  a9=(a9+a53);
  a58=(a58-a9);
  a9=(a11*a58);
  a38=(a38+a9);
  a9=(a14*a58);
  a9=(a38-a9);
  a9=(a1*a9);
  a53=(a4*a20);
  a9=(a9-a53);
  a53=(a13*a58);
  a53=(a37+a53);
  a45=(a22*a53);
  a51=(a23*a7);
  a45=(a45+a51);
  a25=(a25+a45);
  a27=(a27*a25);
  a23=(a23*a53);
  a22=(a22*a7);
  a23=(a23-a22);
  a23=(a23-a28);
  a28=(a30*a23);
  a27=(a27-a28);
  a28=2.8571428571428570e-01;
  a48=(a28*a48);
  a22=(a46*a23);
  a22=(a22+a58);
  a48=(a48-a22);
  a48=(a58+a48);
  a22=(a31*a48);
  a27=(a27+a22);
  a22=(a35*a48);
  a27=(a27-a22);
  a27=(a1*a27);
  a22=(a26*a44);
  a27=(a27-a22);
  a9=(a9+a27);
  a9=(a0+a9);
  a22=(a9/a16);
  a55=(a3*a55);
  a57=(a2*a57);
  a55=(a55+a57);
  a57=(a55/a54);
  a57=(a57/a16);
  a53=20.;
  a45=(a53*a8);
  a51=(a11*a45);
  a50=(a13*a19);
  a59=(a13*a43);
  a50=(a50+a59);
  a0=(a0*a50);
  a59=(a13*a14);
  a13=(a13*a35);
  a59=(a59+a13);
  a45=(a59*a45);
  a0=(a0-a45);
  a45=(a1*a18);
  a13=(a1*a4);
  a47=(a19*a13);
  a47=(a45+a47);
  a49=(a20-a47);
  a41=(a1*a41);
  a60=(a1*a26);
  a61=(a43*a60);
  a61=(a41+a61);
  a62=(a44-a61);
  a49=(a49+a62);
  a63=(a49*a5);
  a0=(a0+a63);
  a51=(a51+a0);
  a0=(a57*a51);
  a22=(a22-a0);
  a0=(a52*a24);
  a63=(a28*a0);
  a64=(a11/a54);
  a52=(a52*a30);
  a65=(a28*a52);
  a64=(a64*a65);
  a0=(a40*a0);
  a52=(a31*a52);
  a0=(a0+a52);
  a56=(a56+a0);
  a56=(a28*a56);
  a56=(a56/a54);
  a64=(a64-a56);
  a55=(a55*a64);
  a63=(a63+a55);
  a63=(a63/a16);
  a55=-9.8100000000000005e+00;
  a42=(a1*a42);
  a55=(a55*a42);
  a34=(a1*a34);
  a8=(a34*a8);
  a55=(a55-a8);
  a8=(a62*a5);
  a55=(a55+a8);
  a8=(a63*a55);
  a22=(a22-a8);
  a22=(-a22);
  if (res[0]!=0) res[0][3]=a22;
  a54=(1./a54);
  a6=(a3*a6);
  a21=(a2*a21);
  a6=(a6+a21);
  a21=(a6*a57);
  a54=(a54+a21);
  a21=(a54*a51);
  a22=(a57*a9);
  a21=(a21-a22);
  a6=(a6*a63);
  a64=(a64+a6);
  a6=(a64*a55);
  a21=(a21+a6);
  a21=(-a21);
  if (res[0]!=0) res[0][4]=a21;
  a51=(a64*a51);
  a9=(a63*a9);
  a51=(a51-a9);
  a9=(a46*a24);
  a21=(a40*a9);
  a46=(a46*a30);
  a30=(a31*a46);
  a21=(a21+a30);
  a17=(a17+a21);
  a17=(a17*a64);
  a9=(a9*a63);
  a21=(a11*a64);
  a46=(a46*a21);
  a9=(a9+a46);
  a17=(a17-a9);
  a28=(a28-a17);
  a55=(a28*a55);
  a51=(a51+a55);
  a51=(-a51);
  if (res[0]!=0) res[0][5]=a51;
  a51=(a58*a31);
  a51=(a51-a38);
  a38=(a4*a40);
  a38=(a18+a38);
  a55=(a4*a38);
  a51=(a51+a55);
  a51=(a1*a51);
  a55=(a51+a27);
  a17=(a55/a16);
  a3=(a3*a37);
  a2=(a2*a7);
  a3=(a3+a2);
  a58=(a58*a40);
  a3=(a3+a58);
  a58=(a4*a31);
  a58=(a58-a12);
  a4=(a4*a58);
  a3=(a3-a4);
  a3=(a1*a3);
  a24=(a24*a23);
  a33=(a33*a25);
  a24=(a24+a33);
  a33=(a40*a48);
  a24=(a24-a33);
  a48=(a43*a48);
  a24=(a24+a48);
  a24=(a1*a24);
  a26=(a26*a36);
  a24=(a24+a26);
  a26=(a3-a24);
  a26=(a11*a26);
  a48=(a43*a51);
  a33=(a35*a3);
  a48=(a48-a33);
  a32=(a1*a32);
  a60=(a35*a60);
  a60=(a32-a60);
  a33=(a60-a36);
  a25=(a33*a58);
  a23=(a62*a38);
  a25=(a25+a23);
  a48=(a48+a25);
  a24=(a31*a24);
  a27=(a40*a27);
  a24=(a24+a27);
  a24=(a48+a24);
  a26=(a26+a24);
  a24=(a57*a26);
  a17=(a17-a24);
  a3=(a31*a3);
  a51=(a40*a51);
  a3=(a3-a51);
  a3=(a3+a48);
  a48=(a63*a3);
  a17=(a17-a48);
  a17=(-a17);
  if (res[0]!=0) res[0][6]=a17;
  a17=(a54*a26);
  a48=(a57*a55);
  a17=(a17-a48);
  a48=(a64*a3);
  a17=(a17+a48);
  a17=(-a17);
  if (res[0]!=0) res[0][7]=a17;
  a26=(a64*a26);
  a55=(a63*a55);
  a26=(a26-a55);
  a3=(a28*a3);
  a26=(a26+a3);
  a26=(-a26);
  if (res[0]!=0) res[0][8]=a26;
  a12=(a1*a12);
  a13=(a14*a13);
  a13=(a12-a13);
  a26=(a13-a15);
  a26=(a26+a33);
  a3=(a57*a26);
  a55=(a63*a33);
  a3=(a3+a55);
  if (res[1]!=0) res[1][0]=a3;
  a3=(a54*a26);
  a55=(a64*a33);
  a3=(a3+a55);
  a3=(-a3);
  if (res[1]!=0) res[1][1]=a3;
  a26=(a64*a26);
  a3=(a28*a33);
  a26=(a26+a3);
  a26=(-a26);
  if (res[1]!=0) res[1][2]=a26;
  a13=(a13+a15);
  a60=(a60+a36);
  a13=(a13+a60);
  a36=(a53*a10);
  a13=(a13-a36);
  a15=(a13/a16);
  a18=(a18+a5);
  a53=(a53*a18);
  a47=(a47+a20);
  a61=(a61+a44);
  a47=(a47+a61);
  a47=(a53-a47);
  a47=(a11*a47);
  a49=(a49*a11);
  a44=(a45*a14);
  a20=(a12*a19);
  a44=(a44+a20);
  a14=(a14*a45);
  a19=(a19*a12);
  a14=(a14+a19);
  a44=(a44+a14);
  a14=(a41*a35);
  a19=(a32*a43);
  a14=(a14+a19);
  a41=(a35*a41);
  a32=(a43*a32);
  a41=(a41+a32);
  a14=(a14+a41);
  a44=(a44+a14);
  a49=(a49+a44);
  a50=(a50*a36);
  a59=(a59*a53);
  a50=(a50+a59);
  a49=(a49-a50);
  a47=(a47+a49);
  a49=(a57*a47);
  a15=(a15-a49);
  a49=(a62*a11);
  a50=(a40*a60);
  a59=(a31*a61);
  a50=(a50+a59);
  a50=(a14-a50);
  a49=(a49+a50);
  a42=(a42*a10);
  a34=(a34*a18);
  a42=(a42+a34);
  a49=(a49-a42);
  a42=(a63*a49);
  a15=(a15-a42);
  a15=(-a15);
  if (res[1]!=0) res[1][3]=a15;
  a15=(a54*a47);
  a42=(a57*a13);
  a15=(a15-a42);
  a42=(a64*a49);
  a15=(a15+a42);
  a15=(-a15);
  if (res[1]!=0) res[1][4]=a15;
  a47=(a64*a47);
  a13=(a63*a13);
  a47=(a47-a13);
  a49=(a28*a49);
  a47=(a47+a49);
  a47=(-a47);
  if (res[1]!=0) res[1][5]=a47;
  a58=(a58-a29);
  a58=(a1*a58);
  a60=(a58+a60);
  a29=(a60/a16);
  a39=(a39+a38);
  a1=(a1*a39);
  a61=(a1-a61);
  a11=(a11*a61);
  a43=(a43*a58);
  a35=(a35*a1);
  a43=(a43-a35);
  a62=(a62*a31);
  a33=(a33*a40);
  a62=(a62-a33);
  a62=(a62+a14);
  a43=(a43+a62);
  a11=(a11+a43);
  a62=(a57*a11);
  a29=(a29-a62);
  a31=(a31*a61);
  a40=(a40*a60);
  a31=(a31-a40);
  a31=(a31+a43);
  a43=(a63*a31);
  a29=(a29-a43);
  a29=(-a29);
  if (res[1]!=0) res[1][6]=a29;
  a29=(a54*a11);
  a43=(a57*a60);
  a29=(a29-a43);
  a43=(a64*a31);
  a29=(a29+a43);
  a29=(-a29);
  if (res[1]!=0) res[1][7]=a29;
  a11=(a64*a11);
  a60=(a63*a60);
  a11=(a11-a60);
  a31=(a28*a31);
  a11=(a11+a31);
  a11=(-a11);
  if (res[1]!=0) res[1][8]=a11;
  a16=(1./a16);
  if (res[2]!=0) res[2][0]=a16;
  a57=(-a57);
  if (res[2]!=0) res[2][1]=a57;
  a63=(-a63);
  if (res[2]!=0) res[2][2]=a63;
  if (res[2]!=0) res[2][3]=a57;
  if (res[2]!=0) res[2][4]=a54;
  if (res[2]!=0) res[2][5]=a64;
  if (res[2]!=0) res[2][6]=a63;
  if (res[2]!=0) res[2][7]=a64;
  if (res[2]!=0) res[2][8]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_derivatives_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_derivatives_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real eval_forward_derivatives_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_derivatives_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_derivatives_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_derivatives_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_derivatives_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
