/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generated_dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

/* eval_forward_dynamics:(i0[3],i1[3],i2[3],i3)->(o0[3],o1[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=2.;
  a4=(a1/a3);
  a5=arg[2]? arg[2][0] : 0;
  a6=arg[0]? arg[0][1] : 0;
  a7=cos(a6);
  a8=arg[1]? arg[1][1] : 0;
  a9=sin(a6);
  a10=(a9*a2);
  a11=(a8*a10);
  a12=arg[0]? arg[0][2] : 0;
  a13=cos(a12);
  a14=arg[1]? arg[1][2] : 0;
  a15=(a14+a8);
  a16=sin(a12);
  a17=(a7*a2);
  a18=(a17+a8);
  a19=(a16*a18);
  a20=(a13*a10);
  a19=(a19+a20);
  a20=(a15*a19);
  a21=4.0000000000000002e-01;
  a22=arg[2]? arg[2][2] : 0;
  a23=5.0000000000000000e-01;
  a24=(a23*a15);
  a25=(a19*a24);
  a25=(a22-a25);
  a26=(a21*a25);
  a27=8.0000000000000004e-01;
  a19=(a14*a19);
  a28=(a27*a19);
  a26=(a26-a28);
  a20=(a20+a26);
  a26=(a13*a20);
  a18=(a13*a18);
  a28=(a16*a10);
  a18=(a18-a28);
  a28=(a14*a18);
  a18=(a18+a24);
  a15=(a15*a18);
  a28=(a28-a15);
  a15=(a16*a28);
  a26=(a26+a15);
  a11=(a11+a26);
  a15=(a16*a13);
  a18=(a27*a13);
  a24=(a18*a16);
  a15=(a15-a24);
  a18=(a18*a13);
  a24=casadi_sq(a16);
  a18=(a18+a24);
  a24=(a23+a18);
  a29=1.2500000000000000e+00;
  a30=(a29+a18);
  a31=(a24/a30);
  a32=(a31*a15);
  a32=(a15-a32);
  a33=(a8*a17);
  a34=(a32*a33);
  a35=1.;
  a18=(a35+a18);
  a36=(a31*a24);
  a18=(a18-a36);
  a36=(a8*a10);
  a37=(a18*a36);
  a34=(a34-a37);
  a37=arg[2]? arg[2][1] : 0;
  a38=(a23*a8);
  a10=(a10*a38);
  a26=(a22+a26);
  a10=(a10+a26);
  a10=(a37-a10);
  a26=(a31*a10);
  a34=(a34+a26);
  a11=(a11+a34);
  a11=(a7*a11);
  a28=(a13*a28);
  a20=(a16*a20);
  a28=(a28-a20);
  a17=(a17+a38);
  a17=(a8*a17);
  a28=(a28-a17);
  a17=(a27*a16);
  a38=(a17*a16);
  a20=casadi_sq(a13);
  a38=(a38+a20);
  a38=(a35+a38);
  a20=(a15/a30);
  a15=(a20*a15);
  a38=(a38-a15);
  a15=(a38*a33);
  a34=(a13*a16);
  a17=(a17*a13);
  a34=(a34-a17);
  a24=(a20*a24);
  a34=(a34-a24);
  a24=(a34*a36);
  a15=(a15-a24);
  a24=(a20*a10);
  a15=(a15+a24);
  a28=(a28+a15);
  a28=(a9*a28);
  a11=(a11+a28);
  a11=(a5-a11);
  a28=5.;
  a15=(a7*a18);
  a24=(a9*a34);
  a15=(a15+a24);
  a15=(a15*a7);
  a24=(a7*a32);
  a17=(a9*a38);
  a24=(a24+a17);
  a24=(a24*a9);
  a15=(a15+a24);
  a15=(a28+a15);
  a11=(a11/a15);
  a24=9.8100000000000005e+00;
  a34=(a7*a34);
  a18=(a9*a18);
  a34=(a34-a18);
  a34=(a34*a7);
  a38=(a7*a38);
  a32=(a9*a32);
  a38=(a38-a32);
  a38=(a38*a9);
  a34=(a34+a38);
  a34=(a34/a15);
  a34=(a24*a34);
  a11=(a11-a34);
  a34=(a4*a11);
  a34=(a2+a34);
  a34=(a3*a34);
  a34=(a2+a34);
  a15=(a1/a3);
  a38=(a1/a3);
  a32=(a38*a8);
  a32=(a6+a32);
  a18=cos(a32);
  a17=(a1/a3);
  a10=(a10/a30);
  a30=(a7*a11);
  a26=(a24*a9);
  a30=(a30-a26);
  a30=(a30-a36);
  a31=(a31*a30);
  a9=(a9*a11);
  a7=(a24*a7);
  a9=(a9+a7);
  a33=(a33+a9);
  a20=(a20*a33);
  a31=(a31+a20);
  a10=(a10-a31);
  a31=(a17*a10);
  a31=(a8+a31);
  a32=sin(a32);
  a20=(a17*a11);
  a20=(a2+a20);
  a9=(a32*a20);
  a7=(a31*a9);
  a38=(a38*a14);
  a38=(a12+a38);
  a36=cos(a38);
  a25=(a27*a25);
  a30=(a30+a10);
  a13=(a13*a30);
  a16=(a16*a33);
  a13=(a13-a16);
  a13=(a13-a19);
  a13=(a21*a13);
  a13=(a13+a10);
  a25=(a25-a13);
  a17=(a17*a25);
  a17=(a14+a17);
  a13=(a17+a31);
  a38=sin(a38);
  a20=(a18*a20);
  a19=(a20+a31);
  a16=(a38*a19);
  a33=(a36*a9);
  a16=(a16+a33);
  a33=(a13*a16);
  a30=(a23*a13);
  a26=(a16*a30);
  a26=(a22-a26);
  a39=(a21*a26);
  a16=(a17*a16);
  a40=(a27*a16);
  a39=(a39-a40);
  a33=(a33+a39);
  a39=(a36*a33);
  a19=(a36*a19);
  a40=(a38*a9);
  a19=(a19-a40);
  a17=(a17*a19);
  a19=(a19+a30);
  a13=(a13*a19);
  a17=(a17-a13);
  a13=(a38*a17);
  a39=(a39+a13);
  a7=(a7+a39);
  a13=(a38*a36);
  a19=(a27*a36);
  a30=(a19*a38);
  a13=(a13-a30);
  a19=(a19*a36);
  a30=casadi_sq(a38);
  a19=(a19+a30);
  a30=(a23+a19);
  a40=(a29+a19);
  a41=(a30/a40);
  a42=(a41*a13);
  a42=(a13-a42);
  a43=(a31*a20);
  a44=(a42*a43);
  a19=(a35+a19);
  a45=(a41*a30);
  a19=(a19-a45);
  a45=(a31*a9);
  a46=(a19*a45);
  a44=(a44-a46);
  a46=(a23*a31);
  a9=(a9*a46);
  a39=(a22+a39);
  a9=(a9+a39);
  a9=(a37-a9);
  a39=(a41*a9);
  a44=(a44+a39);
  a7=(a7+a44);
  a7=(a18*a7);
  a17=(a36*a17);
  a33=(a38*a33);
  a17=(a17-a33);
  a20=(a20+a46);
  a31=(a31*a20);
  a17=(a17-a31);
  a31=(a27*a38);
  a20=(a31*a38);
  a46=casadi_sq(a36);
  a20=(a20+a46);
  a20=(a35+a20);
  a46=(a13/a40);
  a13=(a46*a13);
  a20=(a20-a13);
  a13=(a20*a43);
  a33=(a36*a38);
  a31=(a31*a36);
  a33=(a33-a31);
  a30=(a46*a30);
  a33=(a33-a30);
  a30=(a33*a45);
  a13=(a13-a30);
  a30=(a46*a9);
  a13=(a13+a30);
  a17=(a17+a13);
  a17=(a32*a17);
  a7=(a7+a17);
  a7=(a5-a7);
  a17=(a18*a19);
  a13=(a32*a33);
  a17=(a17+a13);
  a17=(a17*a18);
  a13=(a18*a42);
  a30=(a32*a20);
  a13=(a13+a30);
  a13=(a13*a32);
  a17=(a17+a13);
  a17=(a28+a17);
  a7=(a7/a17);
  a33=(a18*a33);
  a19=(a32*a19);
  a33=(a33-a19);
  a33=(a33*a18);
  a20=(a18*a20);
  a42=(a32*a42);
  a20=(a20-a42);
  a20=(a20*a32);
  a33=(a33+a20);
  a33=(a33/a17);
  a33=(a24*a33);
  a7=(a7-a33);
  a33=(a15*a7);
  a33=(a2+a33);
  a33=(a3*a33);
  a34=(a34+a33);
  a33=(a1/a3);
  a17=(a4*a10);
  a17=(a8+a17);
  a17=(a33*a17);
  a17=(a6+a17);
  a20=cos(a17);
  a42=(a1/a3);
  a9=(a9/a40);
  a40=(a18*a7);
  a19=(a24*a32);
  a40=(a40-a19);
  a40=(a40-a45);
  a41=(a41*a40);
  a32=(a32*a7);
  a18=(a24*a18);
  a32=(a32+a18);
  a43=(a43+a32);
  a46=(a46*a43);
  a41=(a41+a46);
  a9=(a9-a41);
  a41=(a42*a9);
  a41=(a8+a41);
  a17=sin(a17);
  a46=(a42*a7);
  a46=(a2+a46);
  a32=(a17*a46);
  a18=(a41*a32);
  a45=(a4*a25);
  a45=(a14+a45);
  a33=(a33*a45);
  a33=(a12+a33);
  a45=cos(a33);
  a26=(a27*a26);
  a40=(a40+a9);
  a36=(a36*a40);
  a38=(a38*a43);
  a36=(a36-a38);
  a36=(a36-a16);
  a36=(a21*a36);
  a36=(a36+a9);
  a26=(a26-a36);
  a42=(a42*a26);
  a42=(a14+a42);
  a36=(a42+a41);
  a33=sin(a33);
  a46=(a20*a46);
  a16=(a46+a41);
  a38=(a33*a16);
  a43=(a45*a32);
  a38=(a38+a43);
  a43=(a36*a38);
  a40=(a23*a36);
  a19=(a38*a40);
  a19=(a22-a19);
  a13=(a21*a19);
  a38=(a42*a38);
  a30=(a27*a38);
  a13=(a13-a30);
  a43=(a43+a13);
  a13=(a45*a43);
  a16=(a45*a16);
  a30=(a33*a32);
  a16=(a16-a30);
  a42=(a42*a16);
  a16=(a16+a40);
  a36=(a36*a16);
  a42=(a42-a36);
  a36=(a33*a42);
  a13=(a13+a36);
  a18=(a18+a13);
  a36=(a33*a45);
  a16=(a27*a45);
  a40=(a16*a33);
  a36=(a36-a40);
  a16=(a16*a45);
  a40=casadi_sq(a33);
  a16=(a16+a40);
  a40=(a23+a16);
  a30=(a29+a16);
  a31=(a40/a30);
  a44=(a31*a36);
  a44=(a36-a44);
  a39=(a41*a46);
  a47=(a44*a39);
  a16=(a35+a16);
  a48=(a31*a40);
  a16=(a16-a48);
  a48=(a41*a32);
  a49=(a16*a48);
  a47=(a47-a49);
  a49=(a23*a41);
  a32=(a32*a49);
  a13=(a22+a13);
  a32=(a32+a13);
  a32=(a37-a32);
  a13=(a31*a32);
  a47=(a47+a13);
  a18=(a18+a47);
  a18=(a20*a18);
  a42=(a45*a42);
  a43=(a33*a43);
  a42=(a42-a43);
  a46=(a46+a49);
  a41=(a41*a46);
  a42=(a42-a41);
  a41=(a27*a33);
  a46=(a41*a33);
  a49=casadi_sq(a45);
  a46=(a46+a49);
  a46=(a35+a46);
  a49=(a36/a30);
  a36=(a49*a36);
  a46=(a46-a36);
  a36=(a46*a39);
  a43=(a45*a33);
  a41=(a41*a45);
  a43=(a43-a41);
  a40=(a49*a40);
  a43=(a43-a40);
  a40=(a43*a48);
  a36=(a36-a40);
  a40=(a49*a32);
  a36=(a36+a40);
  a42=(a42+a36);
  a42=(a17*a42);
  a18=(a18+a42);
  a18=(a5-a18);
  a42=(a20*a16);
  a36=(a17*a43);
  a42=(a42+a36);
  a42=(a42*a20);
  a36=(a20*a44);
  a40=(a17*a46);
  a36=(a36+a40);
  a36=(a36*a17);
  a42=(a42+a36);
  a42=(a28+a42);
  a18=(a18/a42);
  a43=(a20*a43);
  a16=(a17*a16);
  a43=(a43-a16);
  a43=(a43*a20);
  a46=(a20*a46);
  a44=(a17*a44);
  a46=(a46-a44);
  a46=(a46*a17);
  a43=(a43+a46);
  a43=(a43/a42);
  a43=(a24*a43);
  a18=(a18-a43);
  a43=(a1*a18);
  a43=(a2+a43);
  a34=(a34+a43);
  a43=6.;
  a34=(a34/a43);
  a34=(a1*a34);
  a0=(a0+a34);
  if (res[0]!=0) res[0][0]=a0;
  a0=(a4*a10);
  a0=(a8+a0);
  a0=(a3*a0);
  a0=(a8+a0);
  a34=(a15*a9);
  a34=(a8+a34);
  a34=(a3*a34);
  a0=(a0+a34);
  a32=(a32/a30);
  a30=(a20*a18);
  a34=(a24*a17);
  a30=(a30-a34);
  a30=(a30-a48);
  a31=(a31*a30);
  a17=(a17*a18);
  a20=(a24*a20);
  a17=(a17+a20);
  a39=(a39+a17);
  a49=(a49*a39);
  a31=(a31+a49);
  a32=(a32-a31);
  a31=(a1*a32);
  a31=(a8+a31);
  a0=(a0+a31);
  a0=(a0/a43);
  a0=(a1*a0);
  a0=(a6+a0);
  if (res[0]!=0) res[0][1]=a0;
  a4=(a4*a25);
  a4=(a14+a4);
  a4=(a3*a4);
  a4=(a14+a4);
  a0=(a15*a26);
  a0=(a14+a0);
  a0=(a3*a0);
  a4=(a4+a0);
  a19=(a27*a19);
  a30=(a30+a32);
  a45=(a45*a30);
  a33=(a33*a39);
  a45=(a45-a33);
  a45=(a45-a38);
  a45=(a21*a45);
  a45=(a45+a32);
  a19=(a19-a45);
  a45=(a1*a19);
  a45=(a14+a45);
  a4=(a4+a45);
  a4=(a4/a43);
  a4=(a1*a4);
  a4=(a12+a4);
  if (res[0]!=0) res[0][2]=a4;
  a7=(a3*a7);
  a11=(a11+a7);
  a7=(a3*a18);
  a11=(a11+a7);
  a7=(a15*a9);
  a7=(a8+a7);
  a7=(a1*a7);
  a6=(a6+a7);
  a7=cos(a6);
  a4=(a1*a32);
  a4=(a8+a4);
  a6=sin(a6);
  a18=(a1*a18);
  a18=(a2+a18);
  a45=(a6*a18);
  a38=(a4*a45);
  a15=(a15*a26);
  a15=(a14+a15);
  a15=(a1*a15);
  a12=(a12+a15);
  a15=cos(a12);
  a33=(a1*a19);
  a33=(a14+a33);
  a39=(a33+a4);
  a12=sin(a12);
  a18=(a7*a18);
  a30=(a18+a4);
  a0=(a12*a30);
  a31=(a15*a45);
  a0=(a0+a31);
  a31=(a39*a0);
  a49=(a23*a39);
  a17=(a0*a49);
  a17=(a22-a17);
  a20=(a21*a17);
  a0=(a33*a0);
  a48=(a27*a0);
  a20=(a20-a48);
  a31=(a31+a20);
  a20=(a15*a31);
  a30=(a15*a30);
  a48=(a12*a45);
  a30=(a30-a48);
  a33=(a33*a30);
  a30=(a30+a49);
  a39=(a39*a30);
  a33=(a33-a39);
  a39=(a12*a33);
  a20=(a20+a39);
  a38=(a38+a20);
  a39=(a12*a15);
  a30=(a27*a15);
  a49=(a30*a12);
  a39=(a39-a49);
  a30=(a30*a15);
  a49=casadi_sq(a12);
  a30=(a30+a49);
  a49=(a23+a30);
  a29=(a29+a30);
  a48=(a49/a29);
  a34=(a48*a39);
  a34=(a39-a34);
  a42=(a4*a18);
  a46=(a34*a42);
  a30=(a35+a30);
  a44=(a48*a49);
  a30=(a30-a44);
  a44=(a4*a45);
  a16=(a30*a44);
  a46=(a46-a16);
  a23=(a23*a4);
  a45=(a45*a23);
  a22=(a22+a20);
  a45=(a45+a22);
  a37=(a37-a45);
  a45=(a48*a37);
  a46=(a46+a45);
  a38=(a38+a46);
  a38=(a7*a38);
  a33=(a15*a33);
  a31=(a12*a31);
  a33=(a33-a31);
  a18=(a18+a23);
  a4=(a4*a18);
  a33=(a33-a4);
  a4=(a27*a12);
  a18=(a4*a12);
  a23=casadi_sq(a15);
  a18=(a18+a23);
  a35=(a35+a18);
  a18=(a39/a29);
  a39=(a18*a39);
  a35=(a35-a39);
  a39=(a35*a42);
  a23=(a15*a12);
  a4=(a4*a15);
  a23=(a23-a4);
  a49=(a18*a49);
  a23=(a23-a49);
  a49=(a23*a44);
  a39=(a39-a49);
  a49=(a18*a37);
  a39=(a39+a49);
  a33=(a33+a39);
  a33=(a6*a33);
  a38=(a38+a33);
  a5=(a5-a38);
  a38=(a7*a30);
  a33=(a6*a23);
  a38=(a38+a33);
  a38=(a38*a7);
  a33=(a7*a34);
  a39=(a6*a35);
  a33=(a33+a39);
  a33=(a33*a6);
  a38=(a38+a33);
  a28=(a28+a38);
  a5=(a5/a28);
  a23=(a7*a23);
  a30=(a6*a30);
  a23=(a23-a30);
  a23=(a23*a7);
  a35=(a7*a35);
  a34=(a6*a34);
  a35=(a35-a34);
  a35=(a35*a6);
  a23=(a23+a35);
  a23=(a23/a28);
  a23=(a24*a23);
  a5=(a5-a23);
  a11=(a11+a5);
  a11=(a11/a43);
  a11=(a1*a11);
  a2=(a2+a11);
  if (res[1]!=0) res[1][0]=a2;
  a9=(a3*a9);
  a10=(a10+a9);
  a32=(a3*a32);
  a10=(a10+a32);
  a37=(a37/a29);
  a29=(a7*a5);
  a32=(a24*a6);
  a29=(a29-a32);
  a29=(a29-a44);
  a48=(a48*a29);
  a6=(a6*a5);
  a24=(a24*a7);
  a6=(a6+a24);
  a42=(a42+a6);
  a18=(a18*a42);
  a48=(a48+a18);
  a37=(a37-a48);
  a10=(a10+a37);
  a10=(a10/a43);
  a10=(a1*a10);
  a8=(a8+a10);
  if (res[1]!=0) res[1][1]=a8;
  a26=(a3*a26);
  a25=(a25+a26);
  a3=(a3*a19);
  a25=(a25+a3);
  a27=(a27*a17);
  a29=(a29+a37);
  a15=(a15*a29);
  a12=(a12*a42);
  a15=(a15-a12);
  a15=(a15-a0);
  a21=(a21*a15);
  a21=(a21+a37);
  a27=(a27-a21);
  a25=(a25+a27);
  a25=(a25/a43);
  a1=(a1*a25);
  a14=(a14+a1);
  if (res[1]!=0) res[1][2]=a14;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_dynamics_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_dynamics_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real eval_forward_dynamics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_dynamics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_dynamics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_dynamics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_dynamics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
