/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generated_cont_derivatives_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};

/* eval_cont_forward_derivatives:(i0[2],i1[2],i2[2])->(o0[2x2],o1[2x2],o2[2x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=2.8571428571428570e-01;
  a1=-5.;
  a2=arg[0]? arg[0][1] : 0;
  a3=cos(a2);
  a1=(a1*a3);
  a1=(a0*a1);
  a4=1.;
  a5=2.8571428571428577e+00;
  a6=(a5*a3);
  a6=(a6*a3);
  a7=10.;
  a2=sin(a2);
  a8=(a7*a2);
  a8=(a8*a2);
  a6=(a6+a8);
  a4=(a4+a6);
  a1=(a1/a4);
  a6=arg[0]? arg[0][0] : 0;
  a8=arg[2]? arg[2][0] : 0;
  a9=arg[1]? arg[1][1] : 0;
  a10=arg[1]? arg[1][0] : 0;
  a11=(a3*a10);
  a12=(a3*a11);
  a13=(a2*a10);
  a14=(a2*a13);
  a12=(a12+a14);
  a14=5.0000000000000000e-01;
  a15=(a14*a3);
  a16=(a15*a9);
  a16=(a12-a16);
  a16=(a7*a16);
  a17=(a9*a16);
  a18=(a2*a17);
  a19=(a2*a11);
  a20=(a3*a13);
  a19=(a19-a20);
  a20=(a6*a9);
  a20=(a19-a20);
  a14=(a14*a2);
  a14=(a6-a14);
  a21=(a14*a9);
  a21=(a20+a21);
  a21=(a7*a21);
  a22=(a9*a21);
  a23=(a3*a22);
  a18=(a18-a23);
  a23=-1.4285714285714284e+00;
  a24=arg[2]? arg[2][1] : 0;
  a25=(a12*a21);
  a26=(a20*a16);
  a25=(a25-a26);
  a26=(a6*a17);
  a25=(a25-a26);
  a24=(a24-a25);
  a25=(a23*a24);
  a13=(a9*a13);
  a26=(a5*a13);
  a25=(a25-a26);
  a18=(a18+a25);
  a18=(a3*a18);
  a22=(a2*a22);
  a17=(a3*a17);
  a22=(a22+a17);
  a11=(a9*a11);
  a17=(a7*a11);
  a22=(a22-a17);
  a22=(a2*a22);
  a18=(a18-a22);
  a8=(a8-a18);
  a8=(a8/a4);
  a18=9.8100000000000005e+00;
  a5=(a5*a2);
  a5=(a5*a3);
  a22=(a7*a3);
  a22=(a22*a2);
  a5=(a5-a22);
  a5=(a5/a4);
  a5=(a18*a5);
  a8=(a8-a5);
  a5=(a7*a8);
  a22=(a6*a5);
  a5=(a14*a5);
  a17=9.8100000000000009e+01;
  a25=(a17*a15);
  a5=(a5+a25);
  a25=(a7*a12);
  a26=(a7*a9);
  a27=(a15*a26);
  a27=(a25-a27);
  a28=(a27-a16);
  a29=(a28*a10);
  a5=(a5+a29);
  a22=(a22-a5);
  a5=(a1*a22);
  a29=(a3*a8);
  a30=(a18*a2);
  a29=(a29+a30);
  a29=(a29-a13);
  a13=(a2*a29);
  a18=(a18*a3);
  a2=(a2*a8);
  a18=(a18-a2);
  a18=(a18-a11);
  a18=(a3*a18);
  a13=(a13+a18);
  a24=(a0*a24);
  a29=(a23*a29);
  a24=(a24-a29);
  a29=(a6*a24);
  a13=(a13-a29);
  a24=(a14*a24);
  a13=(a13+a24);
  a13=(a7*a13);
  a9=(a9*a16);
  a13=(a13+a9);
  a17=(a17-a13);
  a13=(a17/a4);
  a5=(a5-a13);
  if (res[0]!=0) res[0][2]=a5;
  a17=(a1*a17);
  a23=(a23*a3);
  a23=(a23*a1);
  a0=(a0+a23);
  a22=(a0*a22);
  a17=(a17-a22);
  if (res[0]!=0) res[0][3]=a17;
  a20=(a7*a20);
  a26=(a14*a26);
  a26=(a20+a26);
  a17=(a21-a26);
  a22=(a1*a17);
  if (res[1]!=0) res[1][0]=a22;
  a17=(a0*a17);
  a17=(-a17);
  if (res[1]!=0) res[1][1]=a17;
  a17=(a25*a14);
  a22=(a20*a15);
  a17=(a17+a22);
  a25=(a14*a25);
  a20=(a15*a20);
  a25=(a25+a20);
  a17=(a17+a25);
  a28=(a28*a6);
  a17=(a17-a28);
  a12=(a12+a10);
  a12=(a7*a12);
  a14=(a14*a12);
  a7=(a7*a19);
  a15=(a15*a7);
  a14=(a14+a15);
  a17=(a17-a14);
  a27=(a27+a16);
  a27=(a27-a12);
  a6=(a6*a27);
  a17=(a17-a6);
  a6=(a1*a17);
  a26=(a26+a21);
  a7=(a7-a26);
  a26=(a7/a4);
  a6=(a6-a26);
  if (res[1]!=0) res[1][2]=a6;
  a7=(a1*a7);
  a17=(a0*a17);
  a7=(a7-a17);
  if (res[1]!=0) res[1][3]=a7;
  a4=(1./a4);
  if (res[2]!=0) res[2][0]=a4;
  a1=(-a1);
  if (res[2]!=0) res[2][1]=a1;
  if (res[2]!=0) res[2][2]=a1;
  if (res[2]!=0) res[2][3]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_derivatives(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_derivatives_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_derivatives_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_derivatives_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_derivatives_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_derivatives_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_derivatives_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_derivatives_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_cont_forward_derivatives_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int eval_cont_forward_derivatives_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real eval_cont_forward_derivatives_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_cont_forward_derivatives_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_cont_forward_derivatives_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_cont_forward_derivatives_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_cont_forward_derivatives_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_derivatives_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
