/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generated_dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

/* eval_forward_dynamics:(i0[2],i1[2],i2[2],i3)->(o0[2],o1[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=2.;
  a4=(a1/a3);
  a5=arg[2]? arg[2][0] : 0;
  a6=arg[0]? arg[0][1] : 0;
  a7=cos(a6);
  a8=arg[1]? arg[1][1] : 0;
  a9=sin(a6);
  a10=(a9*a2);
  a11=(a8*a10);
  a12=-5.0000000000000000e-01;
  a13=arg[2]? arg[2][1] : 0;
  a14=(a10*a8);
  a14=(a13+a14);
  a15=(a12*a14);
  a16=5.0000000000000000e-01;
  a10=(a8*a10);
  a17=(a16*a10);
  a15=(a15-a17);
  a11=(a11+a15);
  a11=(a7*a11);
  a15=(a7*a2);
  a17=(a15-a8);
  a17=(a8*a17);
  a15=(a8*a15);
  a17=(a17-a15);
  a17=(a9*a17);
  a11=(a11-a17);
  a11=(a5-a11);
  a17=10.;
  a15=(a16*a7);
  a15=(a15*a7);
  a18=casadi_sq(a9);
  a15=(a15+a18);
  a15=(a17+a15);
  a11=(a11/a15);
  a18=9.8100000000000005e+00;
  a19=(a16*a9);
  a19=(a19*a7);
  a20=(a7*a9);
  a19=(a19-a20);
  a19=(a19/a15);
  a19=(a18*a19);
  a11=(a11-a19);
  a19=(a4*a11);
  a19=(a2+a19);
  a19=(a3*a19);
  a19=(a2+a19);
  a15=(a1/a3);
  a20=(a1/a3);
  a20=(a20*a8);
  a20=(a6+a20);
  a21=cos(a20);
  a22=(a1/a3);
  a14=(a16*a14);
  a7=(a7*a11);
  a9=(a18*a9);
  a7=(a7+a9);
  a7=(a7-a10);
  a7=(a12*a7);
  a14=(a14-a7);
  a7=(a22*a14);
  a7=(a8+a7);
  a20=sin(a20);
  a22=(a22*a11);
  a22=(a2+a22);
  a10=(a20*a22);
  a9=(a7*a10);
  a23=(a10*a7);
  a23=(a13+a23);
  a24=(a12*a23);
  a10=(a7*a10);
  a25=(a16*a10);
  a24=(a24-a25);
  a9=(a9+a24);
  a9=(a21*a9);
  a22=(a21*a22);
  a24=(a22-a7);
  a24=(a7*a24);
  a7=(a7*a22);
  a24=(a24-a7);
  a24=(a20*a24);
  a9=(a9-a24);
  a9=(a5-a9);
  a24=(a16*a21);
  a24=(a24*a21);
  a7=casadi_sq(a20);
  a24=(a24+a7);
  a24=(a17+a24);
  a9=(a9/a24);
  a7=(a16*a20);
  a7=(a7*a21);
  a22=(a21*a20);
  a7=(a7-a22);
  a7=(a7/a24);
  a7=(a18*a7);
  a9=(a9-a7);
  a7=(a15*a9);
  a7=(a2+a7);
  a7=(a3*a7);
  a19=(a19+a7);
  a7=(a1/a3);
  a24=(a4*a14);
  a24=(a8+a24);
  a7=(a7*a24);
  a7=(a6+a7);
  a24=cos(a7);
  a22=(a1/a3);
  a23=(a16*a23);
  a21=(a21*a9);
  a20=(a18*a20);
  a21=(a21+a20);
  a21=(a21-a10);
  a21=(a12*a21);
  a23=(a23-a21);
  a21=(a22*a23);
  a21=(a8+a21);
  a7=sin(a7);
  a22=(a22*a9);
  a22=(a2+a22);
  a10=(a7*a22);
  a20=(a21*a10);
  a25=(a10*a21);
  a25=(a13+a25);
  a26=(a12*a25);
  a10=(a21*a10);
  a27=(a16*a10);
  a26=(a26-a27);
  a20=(a20+a26);
  a20=(a24*a20);
  a22=(a24*a22);
  a26=(a22-a21);
  a26=(a21*a26);
  a21=(a21*a22);
  a26=(a26-a21);
  a26=(a7*a26);
  a20=(a20-a26);
  a20=(a5-a20);
  a26=(a16*a24);
  a26=(a26*a24);
  a21=casadi_sq(a7);
  a26=(a26+a21);
  a26=(a17+a26);
  a20=(a20/a26);
  a21=(a16*a7);
  a21=(a21*a24);
  a22=(a24*a7);
  a21=(a21-a22);
  a21=(a21/a26);
  a21=(a18*a21);
  a20=(a20-a21);
  a21=(a1*a20);
  a21=(a2+a21);
  a19=(a19+a21);
  a21=6.;
  a19=(a19/a21);
  a19=(a1*a19);
  a0=(a0+a19);
  if (res[0]!=0) res[0][0]=a0;
  a4=(a4*a14);
  a4=(a8+a4);
  a4=(a3*a4);
  a4=(a8+a4);
  a0=(a15*a23);
  a0=(a8+a0);
  a0=(a3*a0);
  a4=(a4+a0);
  a25=(a16*a25);
  a24=(a24*a20);
  a7=(a18*a7);
  a24=(a24+a7);
  a24=(a24-a10);
  a24=(a12*a24);
  a25=(a25-a24);
  a24=(a1*a25);
  a24=(a8+a24);
  a4=(a4+a24);
  a4=(a4/a21);
  a4=(a1*a4);
  a4=(a6+a4);
  if (res[0]!=0) res[0][1]=a4;
  a9=(a3*a9);
  a11=(a11+a9);
  a9=(a3*a20);
  a11=(a11+a9);
  a15=(a15*a23);
  a15=(a8+a15);
  a15=(a1*a15);
  a6=(a6+a15);
  a15=cos(a6);
  a9=(a1*a25);
  a9=(a8+a9);
  a6=sin(a6);
  a20=(a1*a20);
  a20=(a2+a20);
  a4=(a6*a20);
  a24=(a9*a4);
  a10=(a4*a9);
  a13=(a13+a10);
  a10=(a12*a13);
  a4=(a9*a4);
  a7=(a16*a4);
  a10=(a10-a7);
  a24=(a24+a10);
  a24=(a15*a24);
  a20=(a15*a20);
  a10=(a20-a9);
  a10=(a9*a10);
  a9=(a9*a20);
  a10=(a10-a9);
  a10=(a6*a10);
  a24=(a24-a10);
  a5=(a5-a24);
  a24=(a16*a15);
  a24=(a24*a15);
  a10=casadi_sq(a6);
  a24=(a24+a10);
  a17=(a17+a24);
  a5=(a5/a17);
  a24=(a16*a6);
  a24=(a24*a15);
  a10=(a15*a6);
  a24=(a24-a10);
  a24=(a24/a17);
  a24=(a18*a24);
  a5=(a5-a24);
  a11=(a11+a5);
  a11=(a11/a21);
  a11=(a1*a11);
  a2=(a2+a11);
  if (res[1]!=0) res[1][0]=a2;
  a23=(a3*a23);
  a14=(a14+a23);
  a3=(a3*a25);
  a14=(a14+a3);
  a16=(a16*a13);
  a15=(a15*a5);
  a18=(a18*a6);
  a15=(a15+a18);
  a15=(a15-a4);
  a12=(a12*a15);
  a16=(a16-a12);
  a14=(a14+a16);
  a14=(a14/a21);
  a1=(a1*a14);
  a8=(a8+a1);
  if (res[1]!=0) res[1][1]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_dynamics_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_dynamics_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real eval_forward_dynamics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_dynamics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_dynamics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_dynamics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_dynamics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
