/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generated_derivatives_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};

/* eval_forward_derivatives:(i0,i1,i2,i3)->(o0,o1,o2,o3,o4,o5) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.;
  a1=arg[3]? arg[3][0] : 0;
  a2=1.6666666666666666e-01;
  a3=2.;
  a4=(a1/a3);
  a5=-2.;
  a6=9.8100000000000005e+00;
  a7=arg[0]? arg[0][0] : 0;
  a8=cos(a7);
  a8=(a6*a8);
  a8=(a5*a8);
  a9=(a4*a8);
  a9=(a3*a9);
  a10=(a1/a3);
  a11=(a1/a3);
  a12=arg[1]? arg[1][0] : 0;
  a13=(a11*a12);
  a13=(a7+a13);
  a14=cos(a13);
  a14=(a6*a14);
  a14=(a5*a14);
  a14=(a10*a14);
  a14=(a3*a14);
  a9=(a9+a14);
  a14=(a1/a3);
  a15=4.;
  a16=arg[2]? arg[2][0] : 0;
  a17=(a15*a16);
  a18=sin(a7);
  a18=(a6*a18);
  a18=(a5*a18);
  a17=(a17+a18);
  a17=(a4*a17);
  a17=(a12+a17);
  a17=(a14*a17);
  a17=(a7+a17);
  a18=cos(a17);
  a8=(a4*a8);
  a8=(a14*a8);
  a8=(a0+a8);
  a18=(a18*a8);
  a18=(a6*a18);
  a18=(a5*a18);
  a18=(a1*a18);
  a9=(a9+a18);
  a9=(a2*a9);
  a9=(a1*a9);
  a9=(a0+a9);
  if (res[0]!=0) res[0][0]=a9;
  a9=3.;
  a18=cos(a13);
  a18=(a18*a11);
  a18=(a6*a18);
  a18=(a5*a18);
  a18=(a10*a18);
  a18=(a0+a18);
  a18=(a3*a18);
  a9=(a9+a18);
  a18=cos(a17);
  a18=(a18*a14);
  a18=(a6*a18);
  a18=(a5*a18);
  a18=(a1*a18);
  a18=(a0+a18);
  a9=(a9+a18);
  a9=(a2*a9);
  a9=(a1*a9);
  if (res[1]!=0) res[1][0]=a9;
  a9=(a15*a4);
  a9=(a3*a9);
  a18=(a15*a10);
  a18=(a3*a18);
  a9=(a9+a18);
  a18=cos(a17);
  a8=(a15*a4);
  a8=(a14*a8);
  a18=(a18*a8);
  a18=(a6*a18);
  a18=(a5*a18);
  a18=(a15+a18);
  a18=(a1*a18);
  a9=(a9+a18);
  a9=(a2*a9);
  a9=(a1*a9);
  if (res[2]!=0) res[2][0]=a9;
  a9=cos(a7);
  a9=(a6*a9);
  a9=(a5*a9);
  a18=cos(a13);
  a18=(a6*a18);
  a18=(a5*a18);
  a8=(a3*a18);
  a8=(a9+a8);
  a19=cos(a17);
  a9=(a4*a9);
  a9=(a14*a9);
  a9=(a0+a9);
  a19=(a19*a9);
  a19=(a6*a19);
  a19=(a5*a19);
  a19=(a3*a19);
  a8=(a8+a19);
  a16=(a15*a16);
  a19=sin(a13);
  a19=(a6*a19);
  a19=(a5*a19);
  a16=(a16+a19);
  a16=(a10*a16);
  a12=(a12+a16);
  a12=(a1*a12);
  a7=(a7+a12);
  a12=cos(a7);
  a18=(a10*a18);
  a18=(a1*a18);
  a18=(a0+a18);
  a12=(a12*a18);
  a12=(a6*a12);
  a12=(a5*a12);
  a8=(a8+a12);
  a8=(a2*a8);
  a8=(a1*a8);
  if (res[3]!=0) res[3][0]=a8;
  a13=cos(a13);
  a13=(a13*a11);
  a13=(a6*a13);
  a13=(a5*a13);
  a11=(a3*a13);
  a8=cos(a17);
  a8=(a8*a14);
  a8=(a6*a8);
  a8=(a5*a8);
  a8=(a3*a8);
  a11=(a11+a8);
  a8=cos(a7);
  a13=(a10*a13);
  a13=(a0+a13);
  a13=(a1*a13);
  a8=(a8*a13);
  a8=(a6*a8);
  a8=(a5*a8);
  a11=(a11+a8);
  a11=(a2*a11);
  a11=(a1*a11);
  a0=(a0+a11);
  if (res[4]!=0) res[4][0]=a0;
  a0=12.;
  a17=cos(a17);
  a4=(a15*a4);
  a14=(a14*a4);
  a17=(a17*a14);
  a17=(a6*a17);
  a17=(a5*a17);
  a17=(a15+a17);
  a3=(a3*a17);
  a0=(a0+a3);
  a7=cos(a7);
  a10=(a15*a10);
  a10=(a1*a10);
  a7=(a7*a10);
  a6=(a6*a7);
  a5=(a5*a6);
  a15=(a15+a5);
  a0=(a0+a15);
  a2=(a2*a0);
  a1=(a1*a2);
  if (res[5]!=0) res[5][0]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_forward_derivatives_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_derivatives_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_derivatives_n_out(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_real eval_forward_derivatives_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_derivatives_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_derivatives_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    case 5: return "o5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_derivatives_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_derivatives_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    case 4: return casadi_s0;
    case 5: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_forward_derivatives_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
