/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generated_dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};

/* eval_forward_dynamics:(i0,i1,i2,i3)->(o0,o1) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a3=2.;
  a4=(a1/a3);
  a5=4.;
  a6=arg[2]? arg[2][0] : 0;
  a7=(a5*a6);
  a8=-2.;
  a9=9.8100000000000005e+00;
  a10=sin(a0);
  a10=(a9*a10);
  a10=(a8*a10);
  a7=(a7+a10);
  a10=(a4*a7);
  a10=(a2+a10);
  a10=(a3*a10);
  a10=(a2+a10);
  a11=(a1/a3);
  a12=(a5*a6);
  a13=(a1/a3);
  a13=(a13*a2);
  a13=(a0+a13);
  a13=sin(a13);
  a13=(a9*a13);
  a13=(a8*a13);
  a12=(a12+a13);
  a13=(a11*a12);
  a13=(a2+a13);
  a13=(a3*a13);
  a10=(a10+a13);
  a13=(a5*a6);
  a14=(a1/a3);
  a4=(a4*a7);
  a4=(a2+a4);
  a14=(a14*a4);
  a14=(a0+a14);
  a14=sin(a14);
  a14=(a9*a14);
  a14=(a8*a14);
  a13=(a13+a14);
  a14=(a1*a13);
  a14=(a2+a14);
  a10=(a10+a14);
  a14=6.;
  a10=(a10/a14);
  a10=(a1*a10);
  a10=(a0+a10);
  if (res[0]!=0) res[0][0]=a10;
  a10=(a3*a12);
  a7=(a7+a10);
  a3=(a3*a13);
  a7=(a7+a3);
  a5=(a5*a6);
  a11=(a11*a12);
  a11=(a2+a11);
  a11=(a1*a11);
  a0=(a0+a11);
  a0=sin(a0);
  a9=(a9*a0);
  a8=(a8*a9);
  a5=(a5+a8);
  a7=(a7+a5);
  a7=(a7/a14);
  a1=(a1*a7);
  a2=(a2+a1);
  if (res[1]!=0) res[1][0]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_forward_dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_dynamics_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int eval_forward_dynamics_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real eval_forward_dynamics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_dynamics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_forward_dynamics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_dynamics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_forward_dynamics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_forward_dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
