/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) generated_cont_dynamics_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};

/* eval_cont_forward_dynamics:(i0[3],i1[3],i2[3])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[2]? arg[2][0] : 0;
  a1=arg[0]? arg[0][1] : 0;
  a2=cos(a1);
  a3=arg[1]? arg[1][1] : 0;
  a1=sin(a1);
  a4=arg[1]? arg[1][0] : 0;
  a5=(a1*a4);
  a6=(a3*a5);
  a7=arg[0]? arg[0][2] : 0;
  a8=cos(a7);
  a9=arg[1]? arg[1][2] : 0;
  a10=(a9+a3);
  a7=sin(a7);
  a4=(a2*a4);
  a11=(a4+a3);
  a12=(a7*a11);
  a13=(a8*a5);
  a12=(a12+a13);
  a13=(a10*a12);
  a14=4.0000000000000002e-01;
  a15=arg[2]? arg[2][2] : 0;
  a16=5.0000000000000000e-01;
  a17=(a16*a10);
  a18=(a12*a17);
  a18=(a15-a18);
  a19=(a14*a18);
  a20=8.0000000000000004e-01;
  a12=(a9*a12);
  a21=(a20*a12);
  a19=(a19-a21);
  a13=(a13+a19);
  a19=(a8*a13);
  a11=(a8*a11);
  a21=(a7*a5);
  a11=(a11-a21);
  a9=(a9*a11);
  a11=(a11+a17);
  a10=(a10*a11);
  a9=(a9-a10);
  a10=(a7*a9);
  a19=(a19+a10);
  a6=(a6+a19);
  a10=(a7*a8);
  a11=(a20*a8);
  a17=(a11*a7);
  a10=(a10-a17);
  a11=(a11*a8);
  a17=casadi_sq(a7);
  a11=(a11+a17);
  a17=(a16+a11);
  a21=1.2500000000000000e+00;
  a21=(a21+a11);
  a22=(a17/a21);
  a23=(a22*a10);
  a23=(a10-a23);
  a24=(a3*a4);
  a25=(a23*a24);
  a26=1.;
  a11=(a26+a11);
  a27=(a22*a17);
  a11=(a11-a27);
  a27=(a3*a5);
  a28=(a11*a27);
  a25=(a25-a28);
  a28=arg[2]? arg[2][1] : 0;
  a16=(a16*a3);
  a5=(a5*a16);
  a15=(a15+a19);
  a5=(a5+a15);
  a28=(a28-a5);
  a5=(a22*a28);
  a25=(a25+a5);
  a6=(a6+a25);
  a6=(a2*a6);
  a9=(a8*a9);
  a13=(a7*a13);
  a9=(a9-a13);
  a4=(a4+a16);
  a3=(a3*a4);
  a9=(a9-a3);
  a3=(a20*a7);
  a4=(a3*a7);
  a16=casadi_sq(a8);
  a4=(a4+a16);
  a26=(a26+a4);
  a4=(a10/a21);
  a10=(a4*a10);
  a26=(a26-a10);
  a10=(a26*a24);
  a16=(a8*a7);
  a3=(a3*a8);
  a16=(a16-a3);
  a17=(a4*a17);
  a16=(a16-a17);
  a17=(a16*a27);
  a10=(a10-a17);
  a17=(a4*a28);
  a10=(a10+a17);
  a9=(a9+a10);
  a9=(a1*a9);
  a6=(a6+a9);
  a0=(a0-a6);
  a6=5.;
  a9=(a2*a11);
  a10=(a1*a16);
  a9=(a9+a10);
  a9=(a9*a2);
  a10=(a2*a23);
  a17=(a1*a26);
  a10=(a10+a17);
  a10=(a10*a1);
  a9=(a9+a10);
  a6=(a6+a9);
  a0=(a0/a6);
  a9=9.8100000000000005e+00;
  a16=(a2*a16);
  a11=(a1*a11);
  a16=(a16-a11);
  a16=(a16*a2);
  a26=(a2*a26);
  a23=(a1*a23);
  a26=(a26-a23);
  a26=(a26*a1);
  a16=(a16+a26);
  a16=(a16/a6);
  a16=(a9*a16);
  a0=(a0-a16);
  if (res[0]!=0) res[0][0]=a0;
  a28=(a28/a21);
  a21=(a2*a0);
  a16=(a9*a1);
  a21=(a21-a16);
  a21=(a21-a27);
  a22=(a22*a21);
  a1=(a1*a0);
  a9=(a9*a2);
  a1=(a1+a9);
  a24=(a24+a1);
  a4=(a4*a24);
  a22=(a22+a4);
  a28=(a28-a22);
  if (res[0]!=0) res[0][1]=a28;
  a20=(a20*a18);
  a21=(a21+a28);
  a8=(a8*a21);
  a7=(a7*a24);
  a8=(a8-a7);
  a8=(a8-a12);
  a14=(a14*a8);
  a14=(a14+a28);
  a20=(a20-a14);
  if (res[0]!=0) res[0][2]=a20;
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_dynamics(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_dynamics_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_dynamics_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_dynamics_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_dynamics_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_dynamics_release(int mem) {
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_dynamics_incref(void) {
}

CASADI_SYMBOL_EXPORT void eval_cont_forward_dynamics_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int eval_cont_forward_dynamics_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int eval_cont_forward_dynamics_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real eval_cont_forward_dynamics_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_cont_forward_dynamics_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* eval_cont_forward_dynamics_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_cont_forward_dynamics_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* eval_cont_forward_dynamics_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int eval_cont_forward_dynamics_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
